// <auto-generated />
using System;
using System.Net;
using Fiscal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fiscal.Persistence.Migrations
{
    [DbContext(typeof(FiscalDbContext))]
    [Migration("20260831025722_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fiscal.Core.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Ambiente")
                        .HasColumnType("smallint")
                        .HasColumnName("ambiente");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("prefixo");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "Ativa");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("acao");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Detalhe")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalhe");

                    b.Property<IPAddress>("IpOrigem")
                        .HasColumnType("inet")
                        .HasColumnName("ip_origem");

                    b.Property<Guid?>("RecursoId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurso_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CriadoEm");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<byte[]>("ChaveDekCriptografada")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("chave_dek_criptografada");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<byte[]>("PfxCriptografado")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pfx_criptografado");

                    b.Property<byte[]>("SenhaCriptografada")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("senha_criptografada");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("thumbprint");

                    b.Property<DateOnly>("ValidoAte")
                        .HasColumnType("date")
                        .HasColumnName("valido_ate");

                    b.HasKey("Id");

                    b.HasIndex("ValidoAte")
                        .HasFilter("ativo = true");

                    b.HasIndex("TenantId", "Thumbprint")
                        .IsUnique();

                    b.ToTable("certificados", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.DocumentoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Ambiente")
                        .HasColumnType("smallint")
                        .HasColumnName("ambiente");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("chave_acesso");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<short?>("Modelo")
                        .HasColumnType("smallint")
                        .HasColumnName("modelo");

                    b.Property<string>("ModoContingencia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modo_contingencia");

                    b.Property<string>("MotivoStatus")
                        .HasColumnType("text")
                        .HasColumnName("motivo_status");

                    b.Property<long?>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.Property<string>("PayloadEntrada")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_entrada");

                    b.Property<string>("ProtocoloAutorizacao")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("protocolo_autorizacao");

                    b.Property<DateTimeOffset?>("ProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa_em");

                    b.Property<short?>("Serie")
                        .HasColumnType("smallint")
                        .HasColumnName("serie");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<string>("XmlAssinado")
                        .HasColumnType("text")
                        .HasColumnName("xml_assinado");

                    b.Property<string>("XmlGerado")
                        .HasColumnType("text")
                        .HasColumnName("xml_gerado");

                    b.Property<string>("XmlRetornoSefaz")
                        .HasColumnType("text")
                        .HasColumnName("xml_retorno_sefaz");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ProximaTentativaEm")
                        .HasFilter("status IN ('PENDENTE','CONTINGENCIA')");

                    b.HasIndex("TenantId", "CriadoEm");

                    b.HasIndex("TenantId", "Tipo", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "Modelo", "Serie", "Numero")
                        .IsUnique();

                    b.ToTable("documentos_fiscais", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.EventoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Justificativa")
                        .HasColumnType("text")
                        .HasColumnName("justificativa");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_evento");

                    b.Property<string>("XmlRetorno")
                        .HasColumnType("text")
                        .HasColumnName("xml_retorno");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId", "TipoEvento", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("eventos_fiscais", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.SequenciaNumeracao", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("Modelo")
                        .HasColumnType("smallint")
                        .HasColumnName("modelo");

                    b.Property<short>("Serie")
                        .HasColumnType("smallint")
                        .HasColumnName("serie");

                    b.Property<short>("Ambiente")
                        .HasColumnType("smallint")
                        .HasColumnName("ambiente");

                    b.Property<long>("UltimoNumero")
                        .HasColumnType("bigint")
                        .HasColumnName("ultimo_numero");

                    b.HasKey("TenantId", "Modelo", "Serie", "Ambiente");

                    b.ToTable("sequencias_numeracao", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AmbientePadrao")
                        .HasColumnType("smallint")
                        .HasColumnName("ambiente_padrao");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CodigoMunicipioIbge")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_municipio_ibge");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<short>("RegimeTributario")
                        .HasColumnType("smallint")
                        .HasColumnName("regime_tributario");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("text")
                        .HasColumnName("webhook_secret");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("text")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.ApiKey", b =>
                {
                    b.HasOne("Fiscal.Core.Entities.Tenant", "Tenant")
                        .WithMany("ApiKeys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Fiscal.Core.Entities.Certificado", b =>
                {
                    b.HasOne("Fiscal.Core.Entities.Tenant", "Tenant")
                        .WithMany("Certificados")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Fiscal.Core.Entities.DocumentoFiscal", b =>
                {
                    b.HasOne("Fiscal.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Fiscal.Core.Entities.EventoFiscal", b =>
                {
                    b.HasOne("Fiscal.Core.Entities.DocumentoFiscal", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("Fiscal.Core.Entities.SequenciaNumeracao", b =>
                {
                    b.HasOne("Fiscal.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fiscal.Core.Entities.Tenant", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Certificados");
                });
#pragma warning restore 612, 618
        }
    }
}
