// <auto-generated />
using System;
using System.Net;
using Fiscal.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fiscal.Persistence.Migrations
{
    [DbContext(typeof(FiscalDbContext))]
    partial class FiscalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fiscal.Core.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Ambiente")
                        .HasColumnType("smallint")
                        .HasColumnName("ambiente");

                    b.Property<bool>("Ativa")
                        .HasColumnType("boolean")
                        .HasColumnName("ativa");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("key_hash");

                    b.Property<string>("Prefixo")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("prefixo");

                    b.Property<DateTimeOffset?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("TenantId", "Ativa");

                    b.ToTable("api_keys", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.Auditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("acao");

                    b.Property<Guid?>("ApiKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("api_key_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Detalhe")
                        .HasColumnType("jsonb")
                        .HasColumnName("detalhe");

                    b.Property<IPAddress>("IpOrigem")
                        .HasColumnType("inet")
                        .HasColumnName("ip_origem");

                    b.Property<Guid?>("RecursoId")
                        .HasColumnType("uuid")
                        .HasColumnName("recurso_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CriadoEm");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<byte[]>("ChaveDekCriptografada")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("chave_dek_criptografada");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<byte[]>("PfxCriptografado")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pfx_criptografado");

                    b.Property<byte[]>("SenhaCriptografada")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("senha_criptografada");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("thumbprint");

                    b.Property<DateOnly>("ValidoAte")
                        .HasColumnType("date")
                        .HasColumnName("valido_ate");

                    b.HasKey("Id");

                    b.HasIndex("ValidoAte")
                        .HasFilter("ativo = true");

                    b.HasIndex("TenantId", "Thumbprint")
                        .IsUnique();

                    b.ToTable("certificados", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.DocumentoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("Ambiente")
                        .HasColumnType("smallint")
                        .HasColumnName("ambiente");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("chave_acesso");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<short?>("Modelo")
                        .HasColumnType("smallint")
                        .HasColumnName("modelo");

                    b.Property<string>("ModoContingencia")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("modo_contingencia");

                    b.Property<string>("MotivoStatus")
                        .HasColumnType("text")
                        .HasColumnName("motivo_status");

                    b.Property<long?>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.Property<string>("PayloadEntrada")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_entrada");

                    b.Property<string>("ProtocoloAutorizacao")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("protocolo_autorizacao");

                    b.Property<string>("ReciboLote")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recibo_lote");

                    b.Property<DateTimeOffset?>("ProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa_em");

                    b.Property<short?>("Serie")
                        .HasColumnType("smallint")
                        .HasColumnName("serie");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("tipo");

                    b.Property<string>("XmlAssinado")
                        .HasColumnType("text")
                        .HasColumnName("xml_assinado");

                    b.Property<string>("XmlGerado")
                        .HasColumnType("text")
                        .HasColumnName("xml_gerado");

                    b.Property<string>("XmlRetornoSefaz")
                        .HasColumnType("text")
                        .HasColumnName("xml_retorno_sefaz");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ProximaTentativaEm")
                        .HasFilter("status IN ('PENDENTE','CONTINGENCIA')");

                    b.HasIndex("TenantId", "CriadoEm");

                    b.HasIndex("TenantId", "Tipo", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "Modelo", "Serie", "Numero")
                        .IsUnique();

                    b.ToTable("documentos_fiscais", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.EventoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("DadosEvento")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_evento");

                    b.Property<Guid?>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Justificativa")
                        .HasColumnType("text")
                        .HasColumnName("justificativa");

                    b.Property<string>("MotivoStatus")
                        .HasColumnType("text")
                        .HasColumnName("motivo_status");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("protocolo");

                    b.Property<DateTimeOffset?>("ProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_evento");

                    b.Property<string>("XmlRetorno")
                        .HasColumnType("text")
                        .HasColumnName("xml_retorno");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoId", "TipoEvento", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "TipoEvento", "IdempotencyKey")
                        .IsUnique()
                        .HasFilter("documento_id IS NULL");

                    b.HasIndex("Status", "ProximaTentativaEm")
                        .HasFilter("status = 'PENDENTE'");

                    b.ToTable("eventos_fiscais", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.ManifestacaoDestinatario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Justificativa")
                        .HasColumnType("text")
                        .HasColumnName("justificativa");

                    b.Property<string>("MotivoStatus")
                        .HasColumnType("text")
                        .HasColumnName("motivo_status");

                    b.Property<Guid>("NotaRecebidaId")
                        .HasColumnType("uuid")
                        .HasColumnName("nota_recebida_id");

                    b.Property<DateTimeOffset?>("ProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa_em");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("protocolo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NotaRecebidaId", "IdempotencyKey")
                        .IsUnique();

                    b.ToTable("manifestacoes", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.NotaRecebida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Chave")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("chave");

                    b.Property<string>("CnpjEmitente")
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj_emitente");

                    b.Property<DateTimeOffset?>("EmitidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("emitida_em");

                    b.Property<string>("ManifestacaoAtual")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("manifestacao_atual");

                    b.Property<string>("NomeEmitente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome_emitente");

                    b.Property<string>("Nsu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("nsu");

                    b.Property<DateTimeOffset>("RecebidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recebida_em");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoSchema")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_schema");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("valor");

                    b.Property<string>("XmlCompleto")
                        .HasColumnType("text")
                        .HasColumnName("xml_completo");

                    b.Property<string>("XmlResumo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("xml_resumo");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Chave")
                        .IsUnique();

                    b.HasIndex("TenantId", "RecebidaEm");

                    b.ToTable("notas_recebidas", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.NsuDistribuicao", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("Ambiente")
                        .HasColumnType("smallint")
                        .HasColumnName("ambiente");

                    b.Property<string>("UltimoNsu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("ultimo_nsu");

                    b.HasKey("TenantId", "Ambiente");

                    b.ToTable("ultimo_nsu", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.SequenciaNumeracao", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<short>("Modelo")
                        .HasColumnType("smallint")
                        .HasColumnName("modelo");

                    b.Property<short>("Serie")
                        .HasColumnType("smallint")
                        .HasColumnName("serie");

                    b.Property<short>("Ambiente")
                        .HasColumnType("smallint")
                        .HasColumnName("ambiente");

                    b.Property<long>("UltimoNumero")
                        .HasColumnType("bigint")
                        .HasColumnName("ultimo_numero");

                    b.HasKey("TenantId", "Modelo", "Serie", "Ambiente");

                    b.ToTable("sequencias_numeracao", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short>("AmbientePadrao")
                        .HasColumnType("smallint")
                        .HasColumnName("ambiente_padrao");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CodigoMunicipioIbge")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("codigo_municipio_ibge");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<byte[]>("CscCriptografado")
                        .HasColumnType("bytea")
                        .HasColumnName("csc_criptografado");

                    b.Property<string>("CscId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("csc_id");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("razao_social");

                    b.Property<short>("RegimeTributario")
                        .HasColumnType("smallint")
                        .HasColumnName("regime_tributario");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("uf");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("text")
                        .HasColumnName("webhook_secret");

                    b.Property<byte[]>("WebhookSecretCriptografado")
                        .HasColumnType("bytea")
                        .HasColumnName("webhook_secret_criptografado");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("text")
                        .HasColumnName("webhook_url");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_estadual");

                    b.Property<string>("InscricaoMunicipal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("inscricao_municipal");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("complemento");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("cep");

                    b.Property<string>("NomeMunicipio")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_municipio");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.WebhookEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<Guid?>("DocumentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_id");

                    b.Property<DateTimeOffset?>("EntregueEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("entregue_em");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo_evento");

                    b.Property<string>("UltimoErro")
                        .HasColumnType("text")
                        .HasColumnName("ultimo_erro");

                    b.Property<int?>("UltimoStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("ultimo_status_code");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ProximaTentativaEm")
                        .HasFilter("status = 'PENDENTE'");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("TenantId", "CriadoEm");

                    b.ToTable("outbox_webhooks", (string)null);
                });

            modelBuilder.Entity("Fiscal.Core.Entities.ApiKey", b =>
                {
                    b.HasOne("Fiscal.Core.Entities.Tenant", "Tenant")
                        .WithMany("ApiKeys")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Fiscal.Core.Entities.Certificado", b =>
                {
                    b.HasOne("Fiscal.Core.Entities.Tenant", "Tenant")
                        .WithMany("Certificados")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Fiscal.Core.Entities.DocumentoFiscal", b =>
                {
                    b.HasOne("Fiscal.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Fiscal.Core.Entities.EventoFiscal", b =>
                {
                    b.HasOne("Fiscal.Core.Entities.DocumentoFiscal", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("Fiscal.Core.Entities.SequenciaNumeracao", b =>
                {
                    b.HasOne("Fiscal.Core.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fiscal.Core.Entities.ManifestacaoDestinatario", b =>
                {
                    b.HasOne("Fiscal.Core.Entities.NotaRecebida", "NotaRecebida")
                        .WithMany()
                        .HasForeignKey("NotaRecebidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotaRecebida");
                });

            modelBuilder.Entity("Fiscal.Core.Entities.WebhookEntrega", b =>
                {
                    b.HasOne("Fiscal.Core.Entities.DocumentoFiscal", "Documento")
                        .WithMany()
                        .HasForeignKey("DocumentoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("Fiscal.Core.Entities.Tenant", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("Certificados");
                });
#pragma warning restore 612, 618
        }
    }
}
